import { useState } from 'react';

import { AppHeader } from './components/AppHeader';
import { GameList } from './components/GameList';
import { LeagueTabs } from './components/LeagueTabs';
import { ScoreboardToolbar } from './components/ScoreboardToolbar';
import { DEFAULT_LEAGUE_ID, LEAGUES } from './config/leagues';
import { useScoreboard } from './hooks/useScoreboard';
import styles from './App.module.css';

export default function App() {
  const [leagueId, setLeagueId] = useState(DEFAULT_LEAGUE_ID);
  // A view preference, not a fetch parameter — we always load the whole league
  // and narrow it here. Kept in App next to leagueId; useScoreboard stays
  // "load one league's games" and nothing more.
  const [foxOnly, setFoxOnly] = useState(false);

  const scoreboard = useScoreboard(leagueId);
  const league = LEAGUES.find((league) => league.id === leagueId) ?? LEAGUES[0];

  // Derived, not stored: recomputed from games + foxOnly every render, so it
  // can never drift out of sync with the toggle.
  const visibleGames = foxOnly
    ? scoreboard.games.filter((game) => game.isOnFox)
    : scoreboard.games;

  return (
    <div className={styles.app}>
      <AppHeader />

      <main className={styles.main}>
        <div className={styles.controlRow}>
          <LeagueTabs activeId={leagueId} onChange={setLeagueId} />
        </div>

        <ScoreboardToolbar
          gameCount={visibleGames.length}
          totalCount={scoreboard.games.length}
          lastUpdated={scoreboard.lastUpdated}
          isRefreshing={scoreboard.isRefreshing}
          onRefresh={scoreboard.refresh}
          disabled={scoreboard.status === 'loading'}
          foxOnly={foxOnly}
          onToggleFox={() => setFoxOnly((on) => !on)}
        />

        <GameList
          status={scoreboard.status}
          games={visibleGames}
          error={scoreboard.error}
          leagueLabel={league.label}
          foxOnly={foxOnly}
          onRetry={scoreboard.refresh}
        />
      </main>

      <footer className={styles.footer}>
        <p>
          Scores from ESPN's public API. AI recaps are generated by MiniMax and
          may be inaccurate. Not affiliated with, endorsed by, or associated with
          FOX or ESPN.
        </p>
      </footer>
    </div>
  );
}
