import { useCallback, useMemo, useState } from 'react';

import { AppHeader } from './components/AppHeader';
import { GameList } from './components/GameList';
import { LeagueTabs } from './components/LeagueTabs';
import {
  ScoreboardToolbar,
  type Filters,
} from './components/ScoreboardToolbar';
import { DEFAULT_LEAGUE_ID, getLeague } from './config/leagues';
import { useScoreboard } from './hooks/useScoreboard';
import { gameHasFavorite, useFavorites } from './state/favorites';
import styles from './App.module.css';

const NO_FILTERS: Filters = { foxOnly: false, favoritesOnly: false };

export default function App() {
  const [leagueId, setLeagueId] = useState(DEFAULT_LEAGUE_ID);
  const [autoRefresh, setAutoRefresh] = useState(true);
  const [filters, setFilters] = useState<Filters>(NO_FILTERS);

  const scoreboard = useScoreboard(leagueId, autoRefresh);
  const { isFavorite, count: favoriteCount } = useFavorites();
  const league = getLeague(leagueId);

  const toggleFilter = useCallback((key: keyof Filters) => {
    setFilters((current) => ({ ...current, [key]: !current[key] }));
  }, []);

  const clearFilters = useCallback(() => setFilters(NO_FILTERS), []);

  // Filtering happens here, above the list, so the toolbar can report both the
  // visible and the total count and the empty state can tell the two apart.
  const visibleGames = useMemo(
    () =>
      scoreboard.games.filter((game) => {
        if (filters.foxOnly && !game.isOnFox) return false;
        if (filters.favoritesOnly && !gameHasFavorite(game, isFavorite)) {
          return false;
        }
        return true;
      }),
    [scoreboard.games, filters, isFavorite],
  );

  return (
    <div className={styles.app}>
      <AppHeader />

      <main className={styles.main}>
        <div className={styles.controlRow}>
          <LeagueTabs activeId={leagueId} onChange={setLeagueId} />
        </div>

        <ScoreboardToolbar
          visibleCount={visibleGames.length}
          totalCount={scoreboard.games.length}
          filters={filters}
          onToggleFilter={toggleFilter}
          favoriteCount={favoriteCount}
          lastUpdated={scoreboard.lastUpdated}
          isRefreshing={scoreboard.isRefreshing}
          autoRefresh={autoRefresh}
          onToggleAutoRefresh={() => setAutoRefresh((on) => !on)}
          onRefresh={scoreboard.refresh}
          disabled={scoreboard.status === 'loading'}
        />

        <GameList
          status={scoreboard.status}
          games={visibleGames}
          totalGames={scoreboard.games.length}
          error={scoreboard.error}
          leagueLabel={league.label}
          onRetry={scoreboard.refresh}
          onClearFilters={clearFilters}
        />
      </main>

      <footer className={styles.footer}>
        <p>
          Scores from ESPN's public API. AI recaps are generated by MiniMax and
          may be inaccurate. Not affiliated with, endorsed by, or associated with
          FOX or ESPN.
        </p>
      </footer>
    </div>
  );
}
