import { useState } from 'react';

import { AppHeader } from './components/AppHeader';
import { GameList } from './components/GameList';
import { LeagueTabs } from './components/LeagueTabs';
import { ScoreboardToolbar } from './components/ScoreboardToolbar';
import { DEFAULT_LEAGUE_ID, getLeague } from './config/leagues';
import { useScoreboard } from './hooks/useScoreboard';
import styles from './App.module.css';

export default function App() {
  const [leagueId, setLeagueId] = useState(DEFAULT_LEAGUE_ID);
  const [autoRefresh, setAutoRefresh] = useState(true);

  const scoreboard = useScoreboard(leagueId, autoRefresh);
  const league = getLeague(leagueId);

  return (
    <div className={styles.app}>
      <AppHeader />

      <main className={styles.main}>
        <div className={styles.controlRow}>
          <LeagueTabs activeId={leagueId} onChange={setLeagueId} />
        </div>

        <ScoreboardToolbar
          gameCount={scoreboard.games.length}
          lastUpdated={scoreboard.lastUpdated}
          isRefreshing={scoreboard.isRefreshing}
          autoRefresh={autoRefresh}
          onToggleAutoRefresh={() => setAutoRefresh((on) => !on)}
          onRefresh={scoreboard.refresh}
          disabled={scoreboard.status === 'loading'}
        />

        <GameList
          status={scoreboard.status}
          games={scoreboard.games}
          error={scoreboard.error}
          leagueLabel={league.label}
          onRetry={scoreboard.refresh}
        />
      </main>

      <footer className={styles.footer}>
        <p>
          Scores from ESPN's public API. AI recaps are generated by MiniMax and
          may be inaccurate. Not affiliated with, endorsed by, or associated with
          FOX or ESPN.
        </p>
      </footer>
    </div>
  );
}
